[stattracker]
stattracker-vm ansible_host=192.168.5.34 ansible_user=stattracker ansible_become=true ansible_become_method=su ansible_become_user=root

[stattracker:vars]
ansible_python_interpreter=/usr/bin/python3
